// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewTarget } from "./ReviewTarget";

export interface Review { text: string, user: string, date: Date, target: ReviewTarget, }